[pl]
  languageName = "Polski"
  contentDir = "content/pl"
  weight = 10

  [pl.params]
    languageISO = "PL"
    languageTag = "pl-PL"
    titleAddition = "Nowoczesna dokumentacja techniczna"
    title = "Entervive Edukacja"
    description = "Entervive dla Edukacji - platforma hostingowa i dokumentacyjna dla nauczycieli oferująca bezpieczne rozwiązania IT w edukacji."
    footer = 'Projekt Edukacyjny <a class="text-muted" href="https://entervive.pl/">Entervive</a>'
