title = "Entervive dla edukacji"
description = "Profesjonalny hosting i wsparcie techniczne dla nauczycieli za 20 zł rocznie"
keywords = [
  "hosting dla nauczycieli",
  "strona edukacyjna",
  "tanio hosting",
  "domena edukacyjna",
  "hosting edukacyjny",
  "hosting dla szkoły",
  "hosting nauczycielski",
  "strona dla nauczycieli",
  "program dla nauczycieli",
  "wsparcie dla nauczycieli",
  "blog edukacyjny",
  "rejestracja w entervive",
  "hosting dla nauczycieli",
  "strona edukacyjna",
  "tanio hosting",
  "domena edukacyjna",
  "hosting edukacyjny",
  "hosting dla szkoły",
  "hosting nauczycielski",
  "strona dla nauczycieli",
  "program dla nauczycieli",
  "wsparcie dla nauczycieli",
  "blog edukacyjny",
  "rejestracja w entervive",
  "jak stworzyć stronę dla nauczyciela",
  "strona internetowa dla szkoły",
  "platforma edukacyjna dla nauczycieli",
  "hosting tanio dla edukacji",
  "wsparcie IT dla nauczycieli",
  "cms dla nauczycieli",
  "jak założyć blog edukacyjny",
  "jak zacząć z WordPress dla nauczycieli",
  "program dla nauczycieli 20 zł rocznie",
  "tanie strony dla nauczycieli",
  "domeny edukacyjne",
  "platforma hostingowa dla nauczycieli",
  "bezpieczny hosting dla szkół",
  "serwery dla edukacji",
  "pakiet edukacyjny hosting",
  "prosty CMS dla nauczycieli",
  "jak zrobić stronę w Ghostly CMS",
  "WordPress Kadence dla edukacji",
  "pomoc w budowie bloga edukacyjnego",
  "edukacja online narzędzia",
  "tworzenie strony z poradnikiem",
  "jak wykupić hosting edukacyjny",
  "nauka zdalna i hosting",
  "usługa hostingowa dla szkół",
  "strony szkolne i hosting"

]
canonical = "https://edu.entervive.pl"

mainSections = ["docs"]

[doks]
  colorMode = "auto"
  colorModeToggler = true
  navbarSticky = true
  containerBreakpoint = "lg"
  navBarButton = false
  navBarButtonUrl = "/docs/informacje-ogólne/entervive-dla-edukacji/"
  navBarButtonText = "Zacznij!"
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = ["legal"]
  showSearch = []
  indexSummary = false
  showDate = false
  showSummary = true
  searchLimit = 99
  alert = false
  alertDismissable = true
  bootstrapJavascript = false
  sectionNav = ["docs"]
  toTopButton = true
  breadcrumbTrail = true
  headlineHash = true
  scrollSpy = true
  multilingualMode = false
  showMissingLanguages = true
  docsVersioning = false
  docsVersion = "1.0"
  headerBar = false
  backgroundDots = true
  sectionFooter = false
  relatedPosts = false
  imageList = true
  imageSingle = true
  editPage = false
  lastMod = false
  repoHost = "GitHub"
  docsRepo = "https://github.com/Entervive/Entervive-dla-edukacji"
  docsRepoBranch = "main"
  docsRepoSubPath = ""

[render_hooks.image]
  errorLevel = "ignore"

[render_hooks.link]
  errorLevel = "ignore"
  highlightBroken = false

[thulite_images]
  [thulite_images.defaults]
    decoding = "async"
    fetchpriority = "auto"
    loading = "lazy"
    widths = [480, 576, 768, 1025, 1200, 1440]
    sizes = "auto"
    process = ""
    lqip = "16x webp q20"

[inline_svg]
  iconSetDir = "tabler-icons"

[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "favicon.png"
    svgIcon = "favicon.svg"
    maskIcon = "mask-icon.svg"
    maskIconColor = "white"
  [seo.schemas]
    type = "Organization"
    logo = "favicon-512x512.png"
    name = "Entervive"
    sameAs = []
    images = ["cover.png"]
    article = []
    newsArticle = []
    blogPosting = ["blog"]
    product = []
