[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "Dokumentacja"
  url = "docs/informacje-ogólne/entervive-dla-edukacji/"
  weight = 10

[[footer]]
  name = "Polityka prywatności"
  url = "/privacy/"
  weight = 10
